site_name: Job Platform Documentation
site_url: https://nakshatra-droid.github.io/job_platform_docs/
theme:
  name: material
  features:
    - navigation.instant
    - content.code.annotate
    - toc.integrate
    - navigation.tabs
  palette:
    - scheme: default
      primary: blue
      accent: indigo

nav:
  - Home: index.md
  - Functional Documentation: functional_documentation.md
  - Use Case Documentation: usecase_documentation.md
  - Technical Documentation:
      - Technical Stack: technical_stack.md
      - Schema Design: schema_design.md
      - Cloud Architecture: cloud_architecture.md
      - Data Flow Diagram: data_flow.md
      - Authentication & Authorization Flow: auth_flow.md

plugins:
  - mermaid2